"""Task 9 end-to-end: a tiny CSUB column through the whole calibration chain.

This is the integration proof that Tasks 2–8 compose. One MF6-gated test
builds a 1x1x2 CSUB model with the builder tools, runs it once to synthesise a
truth target, registers the observed subsidence via
``import_subsidence_observations`` and assembles the full PEST interface with
``setup_calibration`` targeting ``csub:packagedata`` from ``obs_source=
"derived"``. A second test (additionally gated on ``pestpp-ies``) executes the
calibration and asserts it completed with a real phi summary.

Every test here runs MF6 (the base run, and for the derived path the forward
wrapper is only generated by ``_generate_forward_wrapper`` when MF6 exists), so
every test carries ``@requires_mf6``; the IES test additionally carries
``@requires_pestpp_ies``.
"""

from __future__ import annotations

import csv
import datetime
import math
import subprocess
from pathlib import Path

import pandas as pd
import pytest

from groundwater_mcp.tools.builder import (
    _impl_add_boundary_package,
    _impl_add_csub_package,
    _impl_add_dis_package,
    _impl_add_ic_package,
    _impl_add_npf_package,
    _impl_add_oc_package,
    _impl_add_sto_package,
    _impl_create_model,
    _impl_set_simulation,
)
from groundwater_mcp.tools.calibration import (
    _impl_run_pestpp_ies,
    _impl_setup_calibration,
)
from groundwater_mcp.tools.parameterise import _impl_import_subsidence_observations
from groundwater_mcp.tools.postprocess import _impl_read_compaction
from groundwater_mcp.utils import model_store
from groundwater_mcp.utils.workspace import resolve_workspace


def _mf6_available() -> bool:
    try:
        from groundwater_mcp.tools.runner import _find_mf6_binary

        _find_mf6_binary()
        return True
    except RuntimeError:
        return False


def _pestpp_ies_available() -> bool:
    try:
        from groundwater_mcp.tools.calibration import _find_pestpp_binary

        _find_pestpp_binary("pestpp-ies")
        return True
    except RuntimeError:
        return False


requires_mf6 = pytest.mark.skipif(
    not _mf6_available(), reason="MODFLOW 6 binary not installed"
)
requires_pestpp_ies = pytest.mark.skipif(
    not _pestpp_ies_available(), reason="pestpp-ies binary not installed"
)


# ---------------------------------------------------------------------------
# Tiny model
# ---------------------------------------------------------------------------

# The model runs on an elapsed-day axis anchored to a non-January-1 start date,
# mirroring the holdout: the CSUB obs CSV ``time`` column is elapsed days while
# the observations are calendar dates (Critical 1). Period 0 is steady at head
# -1; the GHB then steps the head down each period, driving compaction in the
# two no-delay interbeds (one per layer).
_START_DATE = "1901-02-15"
_PERLEN = [1.0, 365.0, 365.0]
_GHB_HEADS = [-1.0, -2.0, -3.0]


def _elapsed_to_date(elapsed_days: float) -> str:
    start = datetime.date.fromisoformat(_START_DATE)
    return (start + datetime.timedelta(days=float(elapsed_days))).isoformat()


def _build_tiny_csub(tmp_path: Path, name: str) -> str:
    """Build a 1x1, 2-layer column with one no-delay interbed per layer."""
    ws = str(tmp_path / name)
    _impl_create_model(name, ws, "FEET", "DAYS")
    _impl_set_simulation(
        name,
        3,
        list(_PERLEN),
        [1, 1, 1],
        "moderate",
        start_date_time=_START_DATE,
    )
    _impl_add_dis_package(name, 2, 1, 1, 1.0, 1.0, 0.0, [-10.0, -20.0])
    _impl_add_npf_package(
        name, icelltype=1, k=[1.0, 1.0], k33=[1.0, 1.0], save_flows=True
    )
    _impl_add_ic_package(name, strt=[-1.0, -1.0])
    _impl_add_sto_package(
        name, iconvert=0, ss=0.0, sy=0.0, steady_state=[0], save_flows=True
    )
    ghb = {
        per: [
            [(0, 0, 0), _GHB_HEADS[per], 1.0],
            [(1, 0, 0), _GHB_HEADS[per], 1.0],
        ]
        for per in range(3)
    }
    _impl_add_boundary_package(name, "GHB", ghb, None)

    records = [
        [0, [0, 0, 0], "nodelay", 0.0, 0.5, 1.0, 1e-5, 1e-6, 0.2, 1e-6, -1.0],
        [1, [1, 0, 0], "nodelay", 0.0, 0.5, 1.0, 1e-5, 1e-6, 0.2, 1e-6, -1.0],
    ]
    added = _impl_add_csub_package(
        name,
        packagedata=records,
        sgm=[1.7, 1.7],
        sgs=[2.0, 2.0],
        cg_theta=[0.2, 0.2],
        cg_ske_cr=[1e-5, 1e-5],
        head_based=False,
        initial_preconsolidation_head=True,
        specified_initial_interbed_state=True,
        beta=2.2270e-8,
        gammaw=62.48,
        filerecords={"strainib": f"{name}.strainib.csv"},
        observations={
            f"{name}.csub.obs.csv": [
                ("COMPACTION.01", "compaction-cell", (0, 0, 0)),
                ("COMPACTION.02", "compaction-cell", (1, 0, 0)),
            ]
        },
    )
    assert "error" not in added, added
    _impl_add_oc_package(name, None, None, None, None)
    assert model_store.flush_model(name) is True
    return name


def _run_base_and_register_observed(tmp_path: Path, name: str) -> list[float]:
    """Run the model once and register ``base subsidence x 1.05`` as observed.

    The base run both produces the ``<name>.csub.obs.csv`` the derived plan
    matches against and gives a synthetic truth with a known, non-zero residual
    (pestpp-ies aborts on a perfect prior). Returns the observed values.
    """
    from groundwater_mcp.tools.runner import _find_mf6_binary

    exe = _find_mf6_binary()
    proc = subprocess.run(
        [exe], cwd=str(resolve_workspace(name)), capture_output=True, text=True
    )
    assert proc.returncode == 0, proc.stdout[-2000:] + proc.stderr[-1000:]
    assert "Normal termination" in proc.stdout, proc.stdout[-2000:]

    base = _impl_read_compaction(name)
    assert "error" not in base, base

    obs_csv = tmp_path / f"{name}_observed_subsidence.csv"
    values: list[float] = []
    with obs_csv.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["time", "Subsidence_ft"])
        for time, subsidence in zip(base["times"], base["subsidence"]):
            if float(time) <= _PERLEN[0]:
                continue  # period 0 is steady; zero compaction carries no signal
            observed = float(subsidence) * 1.05
            writer.writerow([_elapsed_to_date(time), observed])
            values.append(observed)

    assert len(values) >= 2, base
    registered = _impl_import_subsidence_observations(
        name, str(obs_csv), time_col="time", value_col="Subsidence_ft"
    )
    assert "error" not in registered, registered
    return values


def _csub_spec() -> dict:
    return {
        "ssv": {
            "target": "csub:packagedata",
            "columns": ["ssv_cc", "sse_cr"],
            "lower_factor": 0.05,
            "upper_factor": 20.0,
            "partrans": "none",
        }
    }


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@requires_mf6
def test_tiny_csub_derived_setup_assembles_full_chain(tmp_path):
    """Builder → derived obs → setup_calibration(csub:packagedata) interface."""
    name = _build_tiny_csub(tmp_path, "tiny")
    observed = _run_base_and_register_observed(tmp_path, name)

    setup = _impl_setup_calibration(
        name, _csub_spec(), obs_source="derived", noptmax=2
    )
    assert "error" not in setup, setup
    assert setup["obs_source"] == "derived"
    assert setup["n_observations"] == len(observed) == 2
    # One parameter per (column x interbed): 2 columns x 2 interbeds.
    assert setup["n_adjustable_parameters"] == 4
    assert Path(setup["pst_file"]).exists()

    ws = resolve_workspace(name)
    csub_text = (ws / f"{name}.csub").read_text()
    assert "OPEN/CLOSE" in csub_text
    assert f"{name}.csub_packagedata.dat" in csub_text
    assert Path(setup["target_file"]).name == f"{name}.csub_packagedata.dat"
    assert (ws / setup["target_file"]).exists()
    assert Path(setup["template_file"]).name == f"{name}.csub_packagedata.dat.tpl"

    # Derived observations matched both observed dates against simulated time.
    report = setup["derived_observations"]["subsidence"]
    assert report["n_observations"] == 2
    assert report["n_matched"] == 2
    assert report["skipped_dates"] == []
    assert report["matching_deferred"] is False

    # Derived observations force the stdlib forward wrapper.
    assert setup["forward_wrapper"] is not None
    assert Path(setup["forward_wrapper"]).exists()


@requires_mf6
@requires_pestpp_ies
def test_tiny_csub_calibration_end_to_end(tmp_path):
    """The whole chain: build → register → setup → pestpp-ies completes."""
    name = _build_tiny_csub(tmp_path, "e2etiny")
    _run_base_and_register_observed(tmp_path, name)

    setup = _impl_setup_calibration(
        name, _csub_spec(), obs_source="derived", noptmax=2
    )
    assert "error" not in setup, setup

    out = _impl_run_pestpp_ies(
        name, setup["pst_file"], num_reals=6, num_workers=1
    )
    assert "error" not in out, out
    assert out["converged"] is True, out
    assert out["iterations"] >= 1, out
    # Meaningful phi: the final iteration's ensemble-mean (the .phi.actual.csv
    # `mean` column), not the inflated all-column sum. The synthetic residual is
    # a few percent of a sub-millimetre signal, so phi is small but positive.
    assert math.isfinite(out["final_phi_mean"])
    assert 0.0 < out["final_phi_mean"] < 1.0, out
    phi_csv = resolve_workspace(name) / (
        Path(setup["pst_file"]).stem + ".phi.actual.csv"
    )
    reported = float(pd.read_csv(phi_csv)["mean"].iloc[-1])
    assert out["final_phi_mean"] == pytest.approx(reported)


# ---------------------------------------------------------------------------
# Critical 2 — delay interbeds need Newton (H201 shape)
# ---------------------------------------------------------------------------

_DELAY_PERLEN = [1.0, 1.0, 1.0]
_DELAY_GHB_HEADS = [-1.0, -2.0, -3.0]


def _build_delay_csub(tmp_path: Path, name: str) -> str:
    """A 1x1, 2-layer column with delay AND no-delay interbeds (H201 shape).

    Newton is enabled with the holdout IMS options (``set_simulation(..., 
    newton=True, linear_acceleration="bicgstab", outer_maximum=300,
    under_relaxation="simple")``); without it the coupled CSUB delay solve does
    not converge (Task 1 spike §6.3).
    """
    ws = str(tmp_path / name)
    _impl_create_model(name, ws, "FEET", "DAYS")
    _impl_set_simulation(
        name,
        3,
        list(_DELAY_PERLEN),
        [1, 1, 1],
        "simple",
        newton=True,
        linear_acceleration="bicgstab",
        outer_maximum=300,
        under_relaxation="simple",
    )
    _impl_add_dis_package(name, 2, 1, 1, 1.0, 1.0, 0.0, [-10.0, -20.0])
    _impl_add_npf_package(
        name, icelltype=1, k=[1.0, 1.0], k33=[1.0, 1.0], save_flows=True
    )
    _impl_add_ic_package(name, strt=[-1.0, -1.0])
    _impl_add_sto_package(
        name, iconvert=0, ss=0.0, sy=0.0, steady_state=[0], save_flows=True
    )
    ghb = {
        per: [
            [(0, 0, 0), _DELAY_GHB_HEADS[per], 1.0],
            [(1, 0, 0), _DELAY_GHB_HEADS[per], 1.0],
        ]
        for per in range(3)
    }
    _impl_add_boundary_package(name, "GHB", ghb, None)

    records = [
        [0, [0, 0, 0], "nodelay", 0.0, 0.5, 1.0, 1e-5, 1e-6, 0.2, 1e-6, -1.0],
        [1, [1, 0, 0], "nodelay", 0.0, 0.5, 1.0, 1e-5, 1e-6, 0.2, 1e-6, -1.0],
        [2, [0, 0, 0], "delay", 0.0, 0.5, 1.0, 1e-5, 1e-6, 0.2, 1e-6, -1.0],
    ]
    added = _impl_add_csub_package(
        name,
        packagedata=records,
        ndelaycells=19,
        sgm=[1.7, 1.7],
        sgs=[2.0, 2.0],
        cg_theta=[0.2, 0.2],
        cg_ske_cr=[1e-5, 1e-5],
        head_based=False,
        initial_preconsolidation_head=True,
        specified_initial_interbed_state=True,
        beta=2.2270e-8,
        gammaw=62.48,
        filerecords={"strainib": f"{name}.strainib.csv"},
        observations={
            f"{name}.csub.obs.csv": [
                ("COMPACTION.01", "compaction-cell", (0, 0, 0)),
                ("COMPACTION.02", "compaction-cell", (1, 0, 0)),
                ("PRECONSTRESS.01", "preconstress-cell", (0, 0, 0)),
            ]
        },
    )
    assert "error" not in added, added
    assert added["n_delay_interbeds"] == 1
    _impl_add_oc_package(name, None, None, None, None)
    assert model_store.flush_model(name) is True
    return name


@requires_mf6
def test_delay_interbed_newton_converges(tmp_path):
    """Delay + no-delay interbeds with Newton run to normal termination."""
    from groundwater_mcp.tools.runner import _find_mf6_binary

    name = _build_delay_csub(tmp_path, "delaycsub")
    exe = _find_mf6_binary()
    proc = subprocess.run(
        [exe], cwd=str(resolve_workspace(name)), capture_output=True, text=True
    )
    assert proc.returncode == 0, proc.stdout[-3000:] + proc.stderr[-1000:]
    assert "Normal termination" in proc.stdout, proc.stdout[-3000:]

    compaction = _impl_read_compaction(name)
    assert "error" not in compaction, compaction
    assert len(compaction["times"]) >= 2
    assert any(abs(v) > 0.0 for v in compaction["subsidence"]), compaction
