"""7f-E tests — build-loop write cost (defer writes, flush explicitly).

E1.2: builder calls stage changes and defer the disk write; flush_model (and
      check_model / run_simulation / list_model_files) performs it.
E1.3: the deferred 12-call build completes in under half the eager build's wall
      time on the same fixture grid.

See tasks.md § 7f Tier E and
research/discovery/sessions/2026-08-17-7f-E-build-loop-cost.md.
"""

from __future__ import annotations

import time

import flopy.mf6 as mf6
import pytest

from groundwater_mcp.tools.builder import (
    _impl_add_boundary_package,
    _impl_add_dis_package,
    _impl_add_ic_package,
    _impl_add_npf_package,
    _impl_add_oc_package,
    _impl_add_sto_package,
    _impl_create_model,
    _impl_flush_model,
    _impl_set_simulation,
)
from groundwater_mcp.utils import model_store
from groundwater_mcp.utils.model_store import flush_model
from groundwater_mcp.utils.workspace import resolve_workspace

# The "same fixture grid" used by the E1.1 benchmark and the E1.3 guard test.
FIXTURE_NLAY, FIXTURE_NROW, FIXTURE_NCOL = 5, 100, 120


def _build_12call(name: str, ws: str, nlay: int, nrow: int, ncol: int, eager: bool) -> None:
    """Representative 12-call regional build with raster-style arrays.

    ``eager=True`` flushes after every call (the pre-7f-E behaviour);
    ``eager=False`` flushes once at the end.
    """
    import numpy as np

    top = np.linspace(95.0, 100.0, nrow * ncol, dtype=float).reshape(nrow, ncol)
    botm = [top - 10.0 * (i + 1) for i in range(nlay)]
    k = np.full((nlay, nrow, ncol), 5.0)
    k33 = np.full((nlay, nrow, ncol), 0.5)

    def _call(fn) -> None:
        fn()
        if eager:
            flush_model(name)

    _call(lambda: _impl_create_model(name, ws, "METERS", "DAYS"))
    _call(lambda: _impl_set_simulation(name, 2, [1.0, 9.0], [1, 3], "moderate"))
    _call(lambda: _impl_add_dis_package(name, nlay, nrow, ncol, 250.0, 250.0, top, botm))  # type: ignore[arg-type]
    _call(lambda: _impl_add_npf_package(name, 1, k, k33, True))  # type: ignore[arg-type]
    _call(lambda: _impl_add_ic_package(name, 80.0))
    _call(lambda: _impl_add_sto_package(name, 1, 1e-5, 0.2, [0], True))
    _call(lambda: _impl_add_oc_package(name, None, None, None, None))
    chd = [[[lay, r, 0], 90.0] for lay in range(nlay) for r in range(nrow)]
    _call(lambda: _impl_add_boundary_package(name, "CHD", {"0": chd, "1": chd}, None))
    wel = [[[0, nrow // 2, ncol // 2], -1000.0]]
    _call(lambda: _impl_add_boundary_package(name, "WEL", {"0": wel, "1": wel}, None))
    riv = [[[0, nrow // 4, c], 60.0, 1e4, 50.0] for c in range(0, ncol, 10)]
    _call(lambda: _impl_add_boundary_package(name, "RIV", {"0": riv}, None))
    drn = [[[0, 3 * nrow // 4, c], 40.0, 1e4] for c in range(0, ncol, 10)]
    _call(lambda: _impl_add_boundary_package(name, "DRN", {"0": drn}, None))
    ghb = [[[lay, r, ncol - 1], 50.0, 1e4] for lay in range(nlay) for r in range(nrow)]
    _call(lambda: _impl_add_boundary_package(name, "GHB", {"0": ghb}, None))

    if not eager:
        flush_model(name)


def _snapshot_files(name: str) -> dict[str, bytes]:
    """Snapshot the workspace files, normalising flopy's generation-timestamp
    header line (the only content that legitimately differs between two
    identical builds run at different times)."""
    ws = resolve_workspace(name)
    out: dict[str, bytes] = {}
    for p in sorted(ws.iterdir()):
        if not (p.is_file() and not p.name.startswith(".")):
            continue
        text = p.read_bytes()
        if text.startswith(b"# File generated by"):
            lines = text.split(b"\n", 1)
            if len(lines) == 2:
                text = b"# header normalized\n" + lines[1]
        out[p.name] = text
    return out


# ---------------------------------------------------------------------------
# E1.2 — deferred writes
# ---------------------------------------------------------------------------


def test_build_defers_writes_until_flush(tmp_path, monkeypatch):
    """A 5-call build performs exactly one write_simulation — at the flush."""
    name = "defer_model"
    ws = str(tmp_path / name)

    calls = {"n": 0}
    orig = mf6.MFSimulation.write_simulation

    def counting_write(self, **kwargs):
        calls["n"] += 1
        return orig(self, **kwargs)

    monkeypatch.setattr(mf6.MFSimulation, "write_simulation", counting_write)

    _impl_create_model(name, ws, "METERS", "DAYS")
    assert model_store.is_dirty(name) is True
    _impl_set_simulation(name, 1, [1.0], [1], "simple")
    _impl_add_dis_package(name, 2, 10, 10, 100.0, 100.0, 50.0, [40.0, 30.0])
    _impl_add_npf_package(name, 1, 10.0, 1.0, True)
    _impl_add_ic_package(name, 45.0)

    # Five builder calls, none written
    assert calls["n"] == 0

    result = _impl_flush_model(name)
    assert result["written"] is True
    assert calls["n"] == 1
    assert model_store.is_dirty(name) is False

    # A second flush is a no-op
    assert flush_model(name) is False
    assert calls["n"] == 1


def test_builder_tools_report_written_false(tmp_path):
    """Builder/parameterise-style calls report written:false while deferred
    (7f-E1.2), and flush_model reports written:true."""
    name = "written_model"
    ws = str(tmp_path / name)
    r_create = _impl_create_model(name, ws, "METERS", "DAYS")
    assert r_create["written"] is False
    r_sim = _impl_set_simulation(name, 1, [1.0], [1], "simple")
    assert r_sim["written"] is False
    r_dis = _impl_add_dis_package(name, 1, 5, 5, 100.0, 100.0, 10.0, [0.0])
    assert r_dis["written"] is False
    r_oc = _impl_add_oc_package(name, None, None, None, None)
    assert r_oc["written"] is False
    r_flush = _impl_flush_model(name)
    assert r_flush["written"] is True


def test_runner_and_list_flush_before_operating(tmp_path, monkeypatch):
    """check_model, run_simulation (monkeypatched) and list_model_files flush
    the staged build and report flushed:true (7f-E1.2)."""
    import groundwater_mcp.tools.runner as runner_module
    from groundwater_mcp.tools.builder import _impl_list_model_files
    from groundwater_mcp.tools.runner import _impl_check_model, _impl_run_simulation

    name = "flush_points"
    ws = str(tmp_path / name)
    _impl_create_model(name, ws, "METERS", "DAYS")
    _impl_set_simulation(name, 1, [1.0], [1], "simple")
    _impl_add_dis_package(name, 1, 5, 5, 100.0, 100.0, 10.0, [0.0])
    _impl_add_npf_package(name, 0, 10.0, None, True)
    _impl_add_ic_package(name, 5.5)
    chd = [[[0, r, 0], 8.0] for r in range(5)] + [[[0, r, 4], 3.0] for r in range(5)]
    _impl_add_boundary_package(name, "CHD", {"0": chd}, None)
    _impl_add_oc_package(name, None, None, None, None)

    assert model_store.is_dirty(name) is True
    check = _impl_check_model(name)
    assert check["flushed"] is True
    assert model_store.is_dirty(name) is False
    assert (resolve_workspace(name) / f"{name}.dis").exists()

    # Re-dirty, then a (monkeypatched) run flushes again
    _impl_add_ic_package(name, 6.0)
    assert model_store.is_dirty(name) is True

    monkeypatch.setattr(runner_module, "_find_mf6_binary", lambda: "/fake/mf6")
    sim = model_store.get_sim(name)
    monkeypatch.setattr(sim, "run_simulation", lambda **_kwargs: (True, ["normal termination"]))
    run = _impl_run_simulation(name, silent=True)
    assert run["flushed"] is True
    assert model_store.is_dirty(name) is False

    # list_model_files flushes too
    _impl_add_oc_package(name, None, None, None, None)
    listing = _impl_list_model_files(name)
    assert listing["flushed"] is True
    assert model_store.is_dirty(name) is False


def test_deferred_build_matches_eager_build_byte_identical(tmp_path):
    """The final on-disk file set after a deferred build + flush is
    byte-identical to the same build writing eagerly (7f-E1.2).

    Both builds use the same model name (the registry is cleared between them)
    so the generated files differ only in the write strategy.
    """
    from groundwater_mcp.utils.model_store import invalidate
    from groundwater_mcp.utils.workspace import delete_workspace

    name = "identical_build"
    eager_ws = str(tmp_path / "eager")
    deferred_ws = str(tmp_path / "deferred")

    _build_12call(name, eager_ws, 3, 30, 40, eager=True)
    eager_files = _snapshot_files(name)

    delete_workspace(name, remove_files=True)
    invalidate(name)  # drop the cached sim + mtime snapshot of the removed build

    _build_12call(name, deferred_ws, 3, 30, 40, eager=False)
    deferred_files = _snapshot_files(name)

    assert eager_files == deferred_files


def test_flush_preserves_external_edit_detection(tmp_path, model_name):
    """After a flush, external edits are again detected and the model reloads
    from disk (7f-D4.1 must keep working with deferred writes, 7f-E1.2)."""
    import os
    import time

    from groundwater_mcp.utils.model_store import get_gwf

    ws = str(tmp_path / model_name)
    _impl_create_model(model_name, ws, "METERS", "DAYS")
    _impl_set_simulation(model_name, 1, [1.0], [1], "simple")
    _impl_add_dis_package(model_name, 1, 5, 5, 100.0, 100.0, 10.0, [0.0])
    _impl_add_ic_package(model_name, strt=8.0)
    assert flush_model(model_name) is True

    ws_path = resolve_workspace(model_name)
    ic_file = ws_path / f"{model_name}.ic"
    edited = ic_file.read_text().replace("8.0", "3.0")
    assert edited != ic_file.read_text(), "IC file does not contain 8.0 to edit"
    ic_file.write_text(edited)
    future = time.time() + 10
    os.utime(ic_file, (future, future))

    from groundwater_mcp.tools.builder import _impl_summarise_model

    summary = _impl_summarise_model(model_name)
    assert summary.get("reloaded_from_disk") is True
    gwf = get_gwf(model_name)
    assert float(gwf.ic.strt.array.ravel()[0]) == pytest.approx(3.0)


# ---------------------------------------------------------------------------
# E1.3 — wall-time regression guard
# ---------------------------------------------------------------------------


def test_deferred_build_under_half_eager_baseline(tmp_path):
    """The 12-call build with deferred writes completes in under half the wall
    time of the same build writing eagerly, measured live on the same fixture
    grid (7f-E1.3; baseline recorded in the 7f-E session log ≈ 6.2 s)."""
    # Eager baseline: write after every call (pre-7f-E behaviour).
    eager_name = "bench_eager"
    t0 = time.perf_counter()
    _build_12call(
        eager_name,
        str(tmp_path / eager_name),
        FIXTURE_NLAY,
        FIXTURE_NROW,
        FIXTURE_NCOL,
        eager=True,
    )
    eager_s = time.perf_counter() - t0

    # Deferred: same 12 calls, one flush at the end.
    deferred_name = "bench_deferred"
    t0 = time.perf_counter()
    _build_12call(
        deferred_name,
        str(tmp_path / deferred_name),
        FIXTURE_NLAY,
        FIXTURE_NROW,
        FIXTURE_NCOL,
        eager=False,
    )
    deferred_s = time.perf_counter() - t0

    assert deferred_s < eager_s / 2, (
        f"Deferred build {deferred_s:.2f}s not under half the eager baseline "
        f"{eager_s:.2f}s (recorded E1.1 baseline ~6.2s)"
    )
