"""spec module — declarative model spec, provenance, and scenarios (7f-G).

G1: apply_model_spec / export_model_spec — a single declarative dict describes
    the grid, time, properties, storage, boundaries and output control; the
    spec can be applied to a model in any prior state and diffed.
G2: describe_model / export_model_report — answers "what is this model, where
    did every number come from, and what is unverified?" from the provenance
    ledger + metadata.
G3: clone_model / compare_scenarios — scenario workflow without destroying the
    base model.
"""

from __future__ import annotations

import shutil

import flopy.mf6 as mf6
import numpy as np
from mcp.server.fastmcp import FastMCP

from groundwater_mcp.tools.builder import _impl_summarise_model
from groundwater_mcp.utils import ledger
from groundwater_mcp.utils.grid import get_grid
from groundwater_mcp.utils.model_store import (
    cache_sim,
    flush_model,
    read_meta,
    restore_oc_period_records,
    write_meta,
)
from groundwater_mcp.utils.spec import apply_spec, export_spec
from groundwater_mcp.utils.workspace import create_workspace, resolve_workspace

# ---------------------------------------------------------------------------
# Error helper
# ---------------------------------------------------------------------------


def _err(code: str, message: str, suggestion: str = "") -> dict:
    return {"error": True, "code": code, "message": message, "suggestion": suggestion}


# ---------------------------------------------------------------------------
# G1 — declarative model spec
# ---------------------------------------------------------------------------


def _impl_apply_model_spec(model: str, spec: dict) -> dict:
    result = apply_spec(model, spec)
    return {
        "model": model,
        "changed": result["changed"],
        "unchanged": result["unchanged"],
        "packages": result["packages"],
        "written": False,  # staged; flush at run/check/list/flush_model
    }


def _impl_export_model_spec(model: str) -> dict:
    return {"model": model, "spec": export_spec(model)}


# ---------------------------------------------------------------------------
# I5 — reproducible-script export
# ---------------------------------------------------------------------------


_SCRIPT_TEMPLATE = '''"""Reproducible build of model "{name}" — generated by groundwater-mcp.

Runs in a clean workspace with only flopy + MODFLOW 6 installed. Produces the
same model (and, after run_simulation, the same heads) as the MCP build.
"""

import json
from pathlib import Path

import flopy.mf6 as mf6

SPEC = {spec_literal}

OUT_DIR = Path(__file__).parent
RUN = {{"run": False}}.get("run", False)


def build():
    sim = mf6.MFSimulation(sim_name="mfsim", version="mf6", sim_ws=str(OUT_DIR))
    gwf = mf6.ModflowGwf(sim, modelname="{name}", model_nam_file="{name}.nam")

    time = SPEC["time"]
    mf6.ModflowTdis(
        sim, pname="tdis", time_units=SPEC.get("time_units", "DAYS"),
        nper=time["nper"],
        perioddata=[(time["perlen"][i], time["nstp"][i],
                     time.get("tsmult", 1.0)) for i in range(time["nper"])],
    )
    ims = mf6.ModflowIms(
        sim, pname="ims", complexity=str(time.get("ims_complexity", "moderate")).upper()
    )
    sim.register_ims_package(ims, [gwf.name])

    grid = SPEC["grid"]
    if grid["type"].upper() == "DIS":
        mf6.ModflowGwfdis(
            gwf, nlay=grid["nlay"], nrow=grid["nrow"], ncol=grid["ncol"],
            delr=grid["delr"], delc=grid["delc"], top=grid["top"], botm=grid["botm"],
        )
    else:
        mf6.ModflowGwfdisv(
            gwf, nlay=grid["nlay"], nvert=len(grid["vertices"]),
            vertices=grid["vertices"], cell2d=grid["cell2d"],
            top=grid["top"], botm=grid["botm"],
        )

    props = SPEC.get("properties", {{}}).get("npf")
    if props:
        mf6.ModflowGwfnpf(gwf, icelltype=props["icelltype"], k=props["k"],
                          k33=props.get("k33"), save_flows=bool(props.get("save_flows", True)))
    if "initial_conditions" in SPEC:
        mf6.ModflowGwfic(gwf, strt=SPEC["initial_conditions"]["strt"])
    if "storage" in SPEC:
        sto = SPEC["storage"]
        mf6.ModflowGwfsto(gwf, iconvert=sto["iconvert"], ss=sto["ss"],
                          sy=sto.get("sy"), save_flows=bool(sto.get("save_flows", True)))
    for pkg_name, spd in SPEC.get("boundaries", {{}}).items():
        cls = getattr(mf6, f"ModflowGwf{{pkg_name.lower()}}")
        cls(gwf, stress_period_data={{int(k): v for k, v in spd.items()}}, save_flows=True)
    oc = SPEC.get("output_control")
    if oc:
        mf6.ModflowGwfoc(gwf, head_filerecord=oc.get("head_file", "{name}.hds"),
                         budget_filerecord=oc.get("budget_file", "{name}.cbb"))
    else:
        mf6.ModflowGwfoc(gwf, head_filerecord="{name}.hds",
                         budget_filerecord="{name}.cbb",
                         saverecord=[("HEAD", "ALL"), ("BUDGET", "ALL")])
    sim.write_simulation(silent=True)
    return sim


if __name__ == "__main__":
    sim = build()
    if RUN:
        sim.run_simulation(silent=False)
'''


def _impl_export_reproducible_script(model: str) -> dict:
    import pprint

    spec = export_spec(model)
    spec_literal = pprint.pformat(spec, width=100, sort_dicts=False)
    ws = resolve_workspace(model)
    script = ws / "run.py"
    script.write_text(
        _SCRIPT_TEMPLATE.format(name=model, spec_literal=spec_literal),
        encoding="utf-8",
    )
    return {
        "model": model,
        "script_file": str(script),
        "note": "Pure-flopy rebuild script; run with `python run.py` in a "
        "clean workspace with flopy + MODFLOW 6 installed.",
    }


# ---------------------------------------------------------------------------
# G2 — provenance / describe / report
# ---------------------------------------------------------------------------


def _results_stale(model: str) -> bool:
    """True when the latest .hds output is older than any package input file."""
    ws = resolve_workspace(model)
    hds = list(ws.glob("*.hds"))
    if not hds:
        return False
    hds_mtime = max(p.stat().st_mtime for p in hds)
    for p in ws.iterdir():
        if p.is_file() and not p.name.startswith(".") and p.suffix in (
            ".dis", ".disv", ".npf", ".ic", ".sto", ".tdis", ".ims", ".oc",
            ".obs", ".wel", ".chd", ".riv", ".drn", ".ghb", ".rch", ".evt",
            ".sfr", ".nam",
        ):
            if p.stat().st_mtime > hds_mtime:
                return True
    return False


def _default_valued_packages(model: str) -> list[str]:
    """Packages whose key arrays are uniform (scalar, never sourced)."""
    from groundwater_mcp.utils.model_store import get_gwf

    gwf = get_gwf(model)
    meta = read_meta(model)
    provenance = meta.get("provenance", {})
    defaults: list[str] = []
    npf = gwf.get_package("npf")
    if npf is not None and "k" not in provenance:
        k = np.asarray(npf.k.array)
        if k.ndim == 0 or float(np.ptp(k)) == 0.0:
            defaults.append("npf.k (uniform/default)")
    dis = get_grid(gwf)
    if dis is not None and "top" not in provenance:
        top = np.asarray(dis.top.array)
        if top.ndim == 0 or float(np.ptp(top)) == 0.0:
            pkg_type = str(getattr(dis, "package_type", "dis")).lower()
            defaults.append(f"{pkg_type}.top (uniform/default)")
    return defaults


def _impl_describe_model(model: str) -> dict:
    summary = _impl_summarise_model(model)
    ws = resolve_workspace(model)
    meta = read_meta(model)
    provenance = meta.get("provenance", {})
    records = ledger.read_records(model)

    has_run = any(p for ext in (".hds", ".hed") for p in ws.rglob(f"*{ext}"))
    last_run = None
    for r in reversed(records):
        if r.get("tool") == "run_simulation":
            last_run = r
            break

    return {
        "model": model,
        "workspace": summary["workspace"],
        "units": meta.get("units"),
        "time_units": meta.get("time_units"),
        "grid": summary["grid"],
        "packages": summary["packages"],
        "boundary_types": summary["boundary_types"],
        "data_sources": provenance,
        "observations": summary["observations"],
        "unverified_defaults": _default_valued_packages(model),
        "has_run": has_run,
        "last_run": last_run,
        "results_stale": _results_stale(model),
        "ledger_entries": len(records),
    }


def _impl_export_model_report(model: str) -> dict:
    from groundwater_mcp.tools.postprocess import (
        _compute_obs_fit,
        _impl_compute_water_balance,
    )

    ws = resolve_workspace(model)
    desc = _impl_describe_model(model)
    lines: list[str] = []
    lines.append(f"# Model report: {model}")
    lines.append("")
    lines.append(f"- Workspace: `{desc['workspace']}`")
    lines.append(f"- Units: {desc['units']} / time {desc['time_units']}")
    lines.append(f"- Grid: {desc['grid'] or 'not set'}")
    lines.append(f"- Packages: {', '.join(desc['packages']) or 'none'}")
    lines.append(f"- Boundaries: {', '.join(desc['boundary_types']) or 'none'}")
    lines.append(f"- Has run: {desc['has_run']} — results stale: {desc['results_stale']}")
    lines.append("")

    lines.append("## Data sources")
    lines.append("")
    if desc["data_sources"]:
        lines.append("| Component | Source | Tool |")
        lines.append("|---|---|---|")
        for key, entry in desc["data_sources"].items():
            lines.append(f"| {key} | `{entry.get('source', '')}` | {entry.get('tool', '')} |")
    else:
        lines.append("None registered.")
    lines.append("")

    lines.append("## Observation fit")
    lines.append("")
    fit = _compute_obs_fit(model)
    if fit:
        lines.append(f"- n={fit['n']}, RMSE={fit['rmse']:.3g}, bias={fit['bias']:.3g}, "
                     f"MAE={fit['mae']:.3g}, R²={fit['r2'] if fit['r2'] is not None else 'n/a'}")
    else:
        lines.append("No observation targets or no run yet.")
    lines.append("")

    lines.append("## Water balance")
    lines.append("")
    wb = _impl_compute_water_balance(model, kstpkper=None)
    if isinstance(wb, dict) and not wb.get("error"):
        lines.append("| Term | Inflow | Outflow |")
        lines.append("|---|---|---|")
        for term in sorted(set(wb.get("inflow", {})) | set(wb.get("outflow", {}))):
            lines.append(
                f"| {term} | {wb['inflow'].get(term, 0.0):.6g} "
                f"| {wb['outflow'].get(term, 0.0):.6g} |"
            )
    else:
        lines.append("Not available (run the simulation first).")
    lines.append("")

    lines.append("## Plots")
    lines.append("")
    plots = sorted(p.name for p in ws.glob("*.png"))
    if plots:
        for name in plots:
            lines.append(f"- `{name}`")
    else:
        lines.append("None.")
    lines.append("")

    lines.append("## Tool-call history (provenance ledger)")
    lines.append("")
    for r in ledger.read_records(model):
        lines.append(f"- `{r['tool']}` — {r['change']}")
    lines.append("")

    report_path = ws / f"{model}_report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return {
        "model": model,
        "report_file": str(report_path),
        "sections": [
            "description",
            "data_sources",
            "observation_fit",
            "water_balance",
            "plots",
            "ledger",
        ],
        "has_run": desc["has_run"],
        "results_stale": desc["results_stale"],
    }


# ---------------------------------------------------------------------------
# G3 — scenarios
# ---------------------------------------------------------------------------


def _impl_clone_model(source: str, name: str, workspace: str) -> dict:
    if len(name) > 16:
        raise ValueError(
            f"Model name '{name}' is {len(name)} characters; MODFLOW 6 caps "
            "MODELNAME at 16 characters. Use a shorter name."
        )
    src_ws = resolve_workspace(source)
    flush_model(source)
    dst = create_workspace(name, workspace or None)

    _OUTPUT_SUFFIXES = (".hds", ".cbb", ".cbc", ".lst")
    for f in src_ws.iterdir():
        if not f.is_file() or f.name.startswith("."):
            continue
        if f.suffix in _OUTPUT_SUFFIXES:
            continue
        if f.suffix == ".csv" and ("_obs.csv" in f.name or "_obs_summary" in f.name):
            continue
        shutil.copy2(f, dst / f.name)

    meta = read_meta(source)
    meta["name"] = name
    meta["cloned_from"] = source
    write_meta(name, meta)

    sim = mf6.MFSimulation.load(sim_ws=str(dst), verbosity_level=0)
    restore_oc_period_records(sim, dst)
    cache_sim(name, sim)
    return {
        "model": name,
        "workspace": str(dst),
        "cloned_from": source,
        "model_names": list(sim.model_names),
    }


def _impl_compare_scenarios(model_a: str, model_b: str) -> dict:
    import flopy.utils as fu

    from groundwater_mcp.tools.postprocess import (
        _compute_obs_fit,
        _impl_compute_water_balance,
    )

    def _last_heads(model: str) -> np.ndarray:
        ws = resolve_workspace(model)
        hds_files = list(ws.glob("*.hds"))
        if not hds_files:
            raise FileNotFoundError(f"No .hds output for model '{model}'. Run both models first.")
        hf = fu.HeadFile(str(hds_files[0]))
        kstpkper_list = hf.get_kstpkper()
        return hf.get_data(kstpkper=kstpkper_list[-1])

    heads_a = _last_heads(model_a)
    heads_b = _last_heads(model_b)
    if heads_a.shape != heads_b.shape:
        raise ValueError(
            f"Grid shapes differ ({heads_a.shape} vs {heads_b.shape}) — models are not "
            "directly comparable. Clone one from the other before comparing."
        )

    diff = heads_a - heads_b
    active = (np.abs(diff) < 1e20)
    d = diff[active]
    pcts = {p: float(np.percentile(d, p)) for p in (5, 25, 50, 75, 95)}
    flat_idx = int(np.argmax(np.abs(diff[active])))
    # Map flat index back to (layer, row, col)
    shape = diff.shape
    layer, row, col = np.unravel_index(flat_idx, shape)

    wb_a = _impl_compute_water_balance(model_a, kstpkper=None)
    wb_b = _impl_compute_water_balance(model_b, kstpkper=None)

    def _budget_deltas(wb1, wb2) -> dict:
        terms = sorted(
            set(wb1.get("inflow", {}))
            | set(wb2.get("inflow", {}))
            | set(wb1.get("outflow", {}))
            | set(wb2.get("outflow", {}))
        )
        return {
            term: {
                "inflow_delta": wb1["inflow"].get(term, 0.0) - wb2["inflow"].get(term, 0.0),
                "outflow_delta": wb1["outflow"].get(term, 0.0) - wb2["outflow"].get(term, 0.0),
            }
            for term in terms
        }

    fit_a = _compute_obs_fit(model_a)
    fit_b = _compute_obs_fit(model_b)
    obs_delta = None
    if fit_a and fit_b:
        obs_delta = {
            "rmse_delta": fit_a["rmse"] - fit_b["rmse"],
            "bias_delta": fit_a["bias"] - fit_b["bias"],
        }

    return {
        "model_a": model_a,
        "model_b": model_b,
        "difference": {
            "min": float(d.min()),
            "max": float(d.max()),
            "mean": float(d.mean()),
            "percentiles": pcts,
            "max_abs_at": {"layer": int(layer), "row": int(row), "col": int(col)},
        },
        "budget_deltas": _budget_deltas(wb_a, wb_b),
        "observation_fit_delta": obs_delta,
    }


# ---------------------------------------------------------------------------
# MCP registration
# ---------------------------------------------------------------------------


def register(mcp: FastMCP) -> None:
    """Register spec/scenario tools with the MCP server."""

    @mcp.tool()
    def apply_model_spec(model: str, spec: dict) -> dict:
        """Apply a declarative model spec to a model in any prior state.

        ``spec`` describes the grid, time discretisation, properties,
        storage, boundaries and output control in one dict (see tools.md
        "Model spec" section for the schema). Returns a structured diff of
        what changed (packages added/replaced/unchanged) rather than a bare
        confirmation."""
        try:
            return _impl_apply_model_spec(model, spec)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except ValueError as exc:
            return _err("INVALID_INPUT", str(exc))
        except Exception as exc:
            return _err("SPEC_APPLY_FAILED", str(exc))

    @mcp.tool()
    def export_model_spec(model: str) -> dict:
        """Emit the declarative spec for an existing or adopted model, so it
        can be inspected, diffed, and rebuilt (apply_model_spec)."""
        try:
            return _impl_export_model_spec(model)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except Exception as exc:
            return _err("SPEC_EXPORT_FAILED", str(exc))

    @mcp.tool()
    def export_reproducible_script(model: str) -> dict:
        """Emit a standalone run.py that rebuilds the model in pure flopy with
        no MCP dependency (7f-I5). Proves the MCP is not a lock-in."""
        try:
            return _impl_export_reproducible_script(model)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except Exception as exc:
            return _err("SCRIPT_EXPORT_FAILED", str(exc))

    @mcp.tool()
    def describe_model(model: str) -> dict:
        """Answer "what is this model, where did every number come from, and
        what is unverified?" from the provenance ledger + metadata: data-source
        provenance per array, defaults still in force, whether the run is
        current with the inputs."""
        try:
            return _impl_describe_model(model)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except Exception as exc:
            return _err("DESCRIBE_FAILED", str(exc))

    @mcp.tool()
    def export_model_report(model: str) -> dict:
        """Generate a Markdown report for the model: description, data-source
        provenance table, water balance, observation fit, plots, and the
        tool-call history. The record is the deliverable for consulting or
        regulatory work."""
        try:
            return _impl_export_model_report(model)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except Exception as exc:
            return _err("REPORT_FAILED", str(exc))

    @mcp.tool()
    def clone_model(source: str, name: str, workspace: str = "") -> dict:
        """Copy a model to a new registered workspace so a scenario does not
        destroy the base model. Binary outputs are not copied; run the clone
        to produce fresh outputs."""
        try:
            return _impl_clone_model(source, name, workspace)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except ValueError as exc:
            return _err("MODEL_EXISTS", str(exc), "Use a different clone name.")
        except Exception as exc:
            return _err("CLONE_FAILED", str(exc))

    @mcp.tool()
    def compare_scenarios(model_a: str, model_b: str) -> dict:
        """Compare two run models and return the differences — head-difference
        statistics (min/max/mean/percentiles + the max-difference cell),
        per-boundary budget deltas, and observation-fit deltas — not arrays."""
        try:
            return _impl_compare_scenarios(model_a, model_b)
        except KeyError as exc:
            return _err("MODEL_NOT_FOUND", str(exc), "Run create_model first.")
        except FileNotFoundError as exc:
            return _err("OUTPUT_FILE_MISSING", str(exc), "Run both models first.")
        except ValueError as exc:
            return _err("INVALID_INPUT", str(exc))
        except Exception as exc:
            return _err("COMPARE_FAILED", str(exc))
